User.create(name: "Fulan Bashi", username: "fulan", email: "fulan@gmail.com", birthday: 1980 - 10 - 18, password_digest: "12345hey")
User.create(name: "Test User1", username: "test1", email: "test1@gmail.com", birthday: 2015 - 04 - 28, password_digest: "67890hey")
User.create(name: "Test User2", username: "text2", email: "test2@gmail.com", birthday: 1999 - 05 - 04, password_digest: "984928hey")


Product.create(name: "long-sleeve tunic", description: "this is the definition of modest, breathable, and comfy", price: 45.00, quantity: 5, img_url: "https://eddiebauer.scene7.com/is/image/EddieBauer/D0090150_300C1?$748V1$")
Product.create(name: "short-sleeve tunic", description: "perfect for layering with our long-sleeve undershirt for added style", price: 45.00, quantity: 5, img_url: "https://img-lcwaikiki.mncdn.com/mnresize/1024/-/pim/productimages/20221/5798361/l_20221-s2gt63z8-rq2_a.jpg")
Product.create(name: "loose joggers", description: "this is the definition of modest, breathable, and comfy", price: 45.00, quantity: 5, img_url: "https://m.media-amazon.com/images/I/61MODcqKunL._AC_UL1500_.jpg")
Product.create(name: "straight-legged track pants", description: "this is the definition of modest, breathable, and comfy", price: 45.00, quantity: 5, img_url: "https://assets.adidas.com/images/w_600,f_auto,q_auto/b5496faa67b0475789d3ada1014e3128_9366/Adicolor_Classics_High-Shine_Straight-Leg_Track_Pants_Black_HF7528_21_model.jpg")
Product.create(name: "long-length tunic", description: "this is perfect for utmost modesty", price: 45.00, quantity: 5, img_url: "https://i04.hsncdn.com/is/image/HomeShoppingNetwork/rocs1200/g-by-giuliana-drama-knit-maxi-length-tunic-top-d-2021091009510232~764293_alt20.jpg")
Product.create(name: "breathable leggings", description: "no more sufffocating, skin-tight leggings!", price: 45.00, quantity: 5, img_url: "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1595351420-52536018_252_c.jpg?crop=1xw:1xh;center,top&resize=480%3A%2A")
Product.create(name: "sports hijab", description: "An easy go-to one-piece hijab, takes a second to put on and a second to take off. Great coverage.", price: 45.00, quantity: 5, img_url: "https://images.dickssportinggoods.com/is/image/GolfGalaxy/21ADIWSPRTHJB20XXTHR_Black?qlt=70&wid=600&fmt=pjpeg")
Product.create(name: "wrap-around sports hijab", description: "for those who prefer their faces to be shaped, the wrap-around hijab is the best option for you!", price: 45.00, quantity: 5, img_url: "https://m.media-amazon.com/images/I/516cOxJI1CL._AC_UL1199_.jpg")
Product.create(name: "mom-joggers", description: "the looser the better? I say that's true! We live for comfort.", price: 45.00, quantity: 5, img_url: "https://s7d2.scene7.com/is/image/aeo/0322_4036_001_of?$pdp-m-opt$")
Product.create(name: "maternity straight-legged pants", description: "most comfortable workout pants for pregnant women", price: 45.00, quantity: 5, img_url: "https://media.seraphine.com/catalog/product/cache/07d50f44375582bdbba32b6e24fcd0e3/S/o/Sofia_Black_01_V2.jpg")
Product.create(name: "long-sleeve undershirt", description: "perfect for layering", price: 45.00, quantity: 5, img_url: "https://pyxis.nymag.com/v1/imgs/6d2/7c5/e5f4edc36646ab3fe9fd7dc5df21a343f0-modernboatnecktshirt.2x.rdeep-vertical.w245.png")

Cart.create(order_id: 1)
Cart.create(order_id: 2)
# Cart.create(user_id: 2, order_id: 3)
# Cart.create(user_id: 3, order_id: 4)

Order.create(user_id: 1, checked_out: false)
# Order.create(user_id: 1, checked_out: false)
# Order.create(user_id: 2, checked_out: false)
# Order.create(user_id: 3, checked_out: false)

CartProduct.create(cart_id: 1, product_id: 1, quantity: 1)
CartProduct.create(cart_id: 1, product_id: 4, quantity: 1)
# CartProduct.create(cart_id: 1, product_id: 2, quantity: 1)
# CartProduct.create(cart_id: 2, product_id: 4, quantity: 1)
# CartProduct.create(cart_id: 2, product_id: 6, quantity: 2)
# CartProduct.create(cart_id: 2, product_id: 7, quantity: 1)
# CartProduct.create(cart_id: 3, product_id: 3, quantity: 1)
# CartProduct.create(cart_id: 3, product_id: 9, quantity: 1)
# CartProduct.create(cart_id: 3, product_id: 8, quantity: 2)
# CartProduct.create(cart_id: 4, product_id: 9, quantity: 1)
